### ISSUE TITLE
Using sap control

### ISSUE THREAD

**Issue by mprusov** [sap-linuxlab/community.sap_libs#9]
### Summary

Dear guys,

I try to use sapcontrol module to stop sap system look like:

- name: Restart the system with 'sapcontrol -function RestartSystem'
  community.sap_libs.sapcontrol:
    sysnr: '00'
    function: StopSystem
    parameter: '0'

The task returns the error:

atal: [sappifprdap]: FAILED! => {
    "changed": false,
    "error": "Server raised fault: 'Validation constraint violation: invalid value in element 'softtimeout''",
    "invocation": {
        "module_args": {
            "force": false,
            "function": "StopSystem",
            "hostname": "localhost",
            "parameter": "0",
            "password": null,
            "port": null,
            "sysnr": "01",
            "username": null
        }
    },
    "msg": "Something went wrong connecting to the SAPCONTROL SOAP API.",
    "out": {}
}

How I can pass arguments into the parameter 'parameter'? Would you explain this topic, please?

Best regards,
Mikhail

 

### Issue Type

Documentation Report

### Component Name

 community.sap_libs.sapcontrol

### Ansible Version

```console (paste below)
$ ansible --version

```

### Community.sap_libs Version

```console (paste below)
$ ansible-galaxy collection list community.sap_libs

```
Collection         Version
------------------ -------
community.sap_libs 1.1.0  

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by rainerleber** [comment]
Hi,

Thank for open this issue. Generally "StopSystem" does not need any parameters. The api does not support the parameter and raise the exception.

**Comment by rainerleber** [comment]
Instead the 0 provide one of the following parameters.

ALL|SCS|DIALOG|ABAP|J2EE|TREX|ENQREP|HDB|ALLNOHDB

**Comment by rainerleber** [comment]
@mprusov is your issue still present ?

**Comment by rainerleber** [comment]
closed because inactivity
